# Set config for testing.
DEBUG = False
TESTING = True
SQLALCHEMY_DATABASE_URI = 'sqlite:///data.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
DEBUG_TB_INTERCEPT_REDIRECTS = False
SECRET_KEY = 'TmsDxTm53ViWecv9k6sCNuwS'
